---
spring:
  application:
    name: gateway-service-zuul
  profiles: zuulmaster
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true
---
spring:
  application:
    name: gateway-service-zuul
  profiles: zuuldup
server:
  port: 8885
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true